import os
from pathlib import Path
from typing import Dict, List
import logging

from llamaink.llm.engine import LlamaEngine
from llamaink.llm.prompts import get_prompt_for_file_type, append_disclaimer

logger = logging.getLogger(__name__)


class DBTDocumentationGenerator:
    """
    Generator for DBT documentation based on repository analysis.

    A straightforward approach that analyzes DBT files and generates
    clear documentation for tables, their relationships, and data lineage.
    """

    def __init__(self, llm_engine: LlamaEngine) -> None:
        """
        Initialize the DBT documentation generator.

        Args:
            llm_engine: The LLM engine to use for generation
        """
        self.llm_engine = llm_engine

    def generate(self, repo_path: str, dbt_files: List[str]) -> Dict[str, str]:
        """
        Generate DBT documentation for the repository.

        Args:
            repo_path: Path to the repository
            dbt_files: List of DBT file paths

        Returns:
            Dictionary mapping file paths to content
        """
        repo_name = os.path.basename(os.path.abspath(repo_path))
        docs: Dict[str, str] = {}

        if not dbt_files:
            logger.warning("No DBT files found in repository")
            return docs

        logger.info(f"Processing {len(dbt_files)} DBT files")
        logger.info(f"Extracting content from DBT files: {', '.join(dbt_files)}")
        file_content = self._get_file_content(repo_path, dbt_files)

        logger.info("Generating DBT documentation")
        prompt = get_prompt_for_file_type("dbt", file_content, repo_name=repo_name)
        if self.llm_engine.verbose:
            docs["prompt.txt"] = prompt
            logger.debug(
                f"Prompt for DBT documentation can be found in {os.path.join(repo_path, 'prompt.txt')}"
            )

        # Get max_tokens from the engine config
        max_tokens = getattr(self.llm_engine, "config", None)
        if max_tokens is None:
            max_tokens = 4096
        else:
            max_tokens = getattr(max_tokens, "max_tokens", 4096)

        logger.info(f"Generating documentation with max_tokens={max_tokens}")
        dbt_docs = self.llm_engine.generate(prompt, max_tokens=max_tokens)

        # Ensure the disclaimer is added to the documentation
        if not any(
            line.strip().startswith(
                "*This documentation was automatically generated by"
            )
            for line in dbt_docs.split("\n")
        ):
            dbt_docs = append_disclaimer(dbt_docs)

        docs["dbt.md"] = dbt_docs

        return docs

    def _get_file_content(self, repo_path: str, dbt_files: List[str]) -> str:
        """
        Extract content from DBT files.

        Args:
            repo_path: Path to the repository
            dbt_files: List of DBT file paths

        Returns:
            Combined file content as context string
        """
        repo_path_obj = Path(repo_path)
        file_entries = []

        sorted_files = self._sort_files_by_priority(dbt_files)

        for file_path in sorted_files:
            try:
                full_path = repo_path_obj / file_path
                if not os.path.exists(full_path):
                    continue

                with open(full_path, "r", encoding="utf-8") as f:
                    content = f.read()

                if file_path.endswith(".sql"):
                    file_type = "sql"
                elif file_path.endswith((".yml", ".yaml")):
                    file_type = "yaml"
                else:
                    file_type = ""

                entry = f"File: {file_path}\n```{file_type}\n{content}\n```\n\n"
                file_entries.append(entry)

            except Exception as e:
                logger.warning(f"Error reading file {file_path}: {str(e)}")

        return "\n".join(file_entries)

    def _sort_files_by_priority(self, dbt_files: List[str]) -> List[str]:
        """
        Sort DBT files by priority to ensure the most important ones are first.

        Args:
            dbt_files: List of DBT file paths

        Returns:
            Sorted list of file paths
        """
        project_files = []
        schema_files = []
        sql_files = []
        other_files = []

        for file_path in dbt_files:
            basename = os.path.basename(file_path)
            if basename == "dbt_project.yml":
                project_files.append(file_path)
            elif file_path.endswith((".yml", ".yaml")) and "schema" in basename:
                schema_files.append(file_path)
            elif file_path.endswith(".sql"):
                sql_files.append(file_path)
            else:
                other_files.append(file_path)

        return project_files + schema_files + sql_files + other_files
