from typing import Any

DBT_DOCS_TEMPLATE = """<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are an expert data engineer with extensive experience documenting DBT projects. Your documentation is clear, concise, and highlights the relationships between models and data flows. You structure your documentation with proper Markdown formatting.

<|eot_id|>
<|start_header_id|>user<|end_header_id|>

I need you to analyze this DBT project and create comprehensive documentation for it. The project is named "{repo_name}".

Here's the context:
{context}

Please create documentation with:
1. A title "# DBT Documentation - {repo_name}"
2. A brief introduction explaining the project's purpose
3. A Models section with subsections for each important model
4. An Entity Relationships section
5. A Data Flow section showing data lineage
6. Use proper Markdown formatting with headers and bullet points
7. Keep SQL examples minimal and focus on the key transformations

<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>

"""

DISCLAIMER = """
---

*This documentation was automatically generated by [LlamaInk](https://github.com/j-coluccino/llamaink), a privacy-first documentation tool using local LLMs. While we strive for accuracy, please review this content as LLMs can make mistakes or misinterpret code patterns.*
"""


def get_prompt_for_file_type(file_type: str, context: str, **kwargs: Any) -> str:
    """
    Get the appropriate prompt template for DBT documentation.

    Args:
        file_type: Type of file to generate documentation for (must be "dbt")
        context: Context information to include in the prompt
        **kwargs: Additional parameters to format the prompt template

    Returns:
        Formatted prompt
    """
    if file_type != "dbt":
        raise ValueError(f"Unsupported file type: {file_type}. Only 'dbt' is supported")

    return DBT_DOCS_TEMPLATE.format(context=context, **kwargs)


def append_disclaimer(content: str) -> str:
    """
    Append the disclaimer to generated content.

    Args:
        content: The generated content

    Returns:
        Content with disclaimer appended
    """
    return content + DISCLAIMER
